[build]
target = "index.html"
dist = "dist"

[serve]
address = "0.0.0.0"
port = 8080

# Post-build hook to generate static blog pages
[[hooks]]
stage = "post_build"
command = "sh"
command_arguments = ["-c", "cd /Users/necro/Desktop/Websites\\ and\\ Apps/Portfolio && node generate-blog-pages.js"]
