mod header;
mod about;
mod skills;
mod projects;
mod contact;
mod terminal;
mod matrix_rain;
mod snake;
mod leaderboard;
mod counter;

pub use header::Header;
pub use about::About;
pub use skills::Skills;
pub use projects::Projects;
pub use contact::Contact;
pub use terminal::Terminal;
pub use matrix_rain::MatrixRain;
pub use snake::Snake;
pub use leaderboard::Leaderboard;
pub use counter::{Counter, CounterType};
