mod header;
mod about;
mod skills;
mod projects;
mod contact;
mod terminal;
mod matrix_rain;
mod snake;
mod leaderboard;
mod counter;
mod spotify;
mod streaming;
mod blog_auth;
mod blog_admin;
mod blog_list;
mod blog_post;
mod theme_config;

pub use header::Header;
pub use about::About;
pub use skills::Skills;
pub use projects::Projects;
pub use contact::Contact;
pub use terminal::Terminal;
pub use matrix_rain::MatrixRain;
pub use snake::Snake;
pub use leaderboard::Leaderboard;
pub use counter::{Counter, CounterType, increment_counter, fetch_counter};
pub use spotify::SpotifyWidget;
pub use streaming::Streaming;
pub use blog_auth::{verify_blog_password, verify_blog_credentials, authenticate_admin, logout, get_stored_auth, verify_token, AuthState};
pub use blog_admin::{BlogAdmin, BlogPost};
pub use blog_list::{BlogList, BlogPost as BlogListPost};
pub use blog_post::{BlogPost as BlogPostComponent, BlogPostData};
pub use theme_config::{ThemeConfig, load_theme_config};
